[package]
name = "quasi_macros"
version = "0.7.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"

[lib]
name = "quasi_macros"
plugin = true

[dependencies]
quasi_codegen = { version = "^0.7.0", path = "../quasi_codegen", default-features = false }

[dev-dependencies]
aster = { git = "https://github.com/benashford/aster", branch = "experimental" }
quasi = { version = "^0.7.0", path = "../quasi" }
